### ISSUE TITLE
add to documentation: split configuration

### ISSUE THREAD

**Issue by lazyadmin111** [xundeenergie/exim4-multiaccount#1]
Hey there,

First of all, thank you very much for your great contribution. This was exactly what I was looking for since days, and I found only other ways of doing it, e.g. switching to postfix. This was the best and most easy solution for me concerning this quite common problem.

I installed your approach in a matter of seconds as I am also using debian stable. I have just one little proposal for improval: I had already exim4 installed, and by default it uses the standalone configuration mode and no split configuration files. Your approach is based on the split files however, and it was not clear to me, if your debian package automatically switched to split configuration or not. As it didn't work at once, I changed the configuration file mode to split files via "dpkg-reconfigure exim4-config" and voilà it worked ! :-) Maybe you can add that line to your installation instructions.

Thank you and keep up the great work!

cheers

**Comment by xundeenergie** [comment]
Thank you!

I added this advice.

But be careful, i changed the format of the configfile, where you put in your sender-addresses and smarthost-credentials. And i changed the name, so that nobody looses the information.

And i changed the other files a little.
So i added a acl, that only the right authenticated user can send with allowed from-header.
And you can de/activate all this configs only by using a makro-variable shown in 002_localmacros_multiaccount

I'm not sure, if this acl works correctly for daemons sending emails. But it works for users sending with thunderbird or evolution their mails.

This is still under construction. Be careful.

you can just comment the whole acl in 30_exim4-config_check_mail_multiaccount except the first line with the name and the line with accept.

cheers!
